### ISSUE TITLE
如何使用JLinkDll

### ISSUE THREAD

**Issue by izeng1997** [LX050724/JLinkDll#1]
大佬您好！我想在matlab中使用该dll，发现它需要一个.h文件。请问一下您这个里面是否有JLink_x64.dll的头文件，以及该怎么使用您的代码呢？

非常感谢您！

**Comment by LX050724** [comment]
很抱歉，并没有JLinkDLL的头文件，这份代码本身就是通过文档逆向过来的，使用方法同JLinkSDK，JLink_x64.dll可以从JLink驱动程序安装路径中找到。如果想在Matlab中使用，可以使用该库编译生成的DLL进行一次套娃调用。文档可参阅代码中的注释或安装Doxyge生成网页文档

**Comment by LX050724** [comment]
我还有一个猜想，由于我的库函数名和形参和JLinkSDK中的一致，那就有可能直接使用我这里的包含函数声明以及结构体和枚举声明的头文件替代JLinkSDK的头文件使用，这样在Linux中也可以直接在链接过程直接使用so文件，而不用通过动态加载方式套娃。

**Comment by SummerFalls** [comment]
我整了一套 JLINK SDK，还是很不错的，值得购买。
